### ISSUE TITLE
Polygon layer

### ISSUE THREAD

**Issue by miszokienka** [mkondratyev85/raster_tracer#10]
It would be very useful if plugin can write to polygon layer, creating polygon from traced object. 
If it's not closed object than it would connect first and last vertex.

**Comment by mkondratyev85** [comment]
I'm not sure if tracing polygons by tracing it's edges as you propose would be a good practice. While QGIS allows you to create a new polygon feature, usually it's better to create several lineal features that surrounds this polygon and then convert them to polygon using `polygonize`. That way is more versatile and flexible.
