### ISSUE TITLE
freezing of the QGIS

### ISSUE THREAD

**Issue by Fowad45** [mkondratyev85/raster_tracer#12]
Hello and Greetings,
Thanks a lot for an awesome plugin. 
I need to highlight an issue that I am currently experiencing, the plugin install and works fine with these versions 3.4.14 and 3.10.5 but after 2 clicks while tracing the software keep freezing. As anyone else experiences the same? happened to me like 6 times now.
I have even let that freezing for like 15 minutes at least but still not unfreezing.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23302597/82156234-4f2cf580-987a-11ea-8693-bce7fad98457.gif)

Details on Input raster data.

file=Georeferenced jp2 and tiff files(tried with both)
projection=DHDN / 3-degree Gauss-Kruger zone 3.
vector file=shapefile
operating system=windows 10 home edition.

with kind regards
& Sorry that's the first time in my life I am pulling an issue on Github.

**Comment by mkondratyev85** [comment]
The plugin freezes when it struggles to find a route between two points. It usually means that the raster file is too large. Try working with a lower resolution or on a smaller raster file.

**Comment by Fowad45** [comment]
Hi
Just a follow-up, python also throws
![rastertracer](https://user-images.githubusercontent.com/23302597/82310567-dc7c6100-99c4-11ea-8f0c-5a7f7153d97a.JPG)
 a  memory issue.

**Comment by mkondratyev85** [comment]
Yes. It looks like the raster file is too large. How much RAM do you have on your computer?

**Comment by Fowad45** [comment]
I have 16GB ram and raster files are like 98MB.

**Comment by mkondratyev85** [comment]
That strange. Could you send me the file so I could reproduce the issue?

**Comment by Fowad45** [comment]
sure, can you drop me an email at 'ahmed.fowad@stud-mail.uni-wuerzburg.de', 
i cant upload on github those files due to being large. 
thanks

**Comment by mkondratyev85** [comment]
I'm not sure what is the reason for you problem. I've tried to work with the file you've send me. When I load it in its original projection (EPSG:5677) the plugin can't find any lines to trace on the map. I believe it has something to do with this projection. 

When I reproject the layer to EPSG:4326 (WGS 84) by using QGIS function under Raster -> Projections -> Reproject, and then load it in QGIS into a project that has projection set to EPSG:4326 (so they both in the same projection) the plugin works fine without any freezing. 

So, I advice you to try this method.
