### ISSUE TITLE
Make smoothing optional

### ISSUE THREAD

**Issue by havatv** [mkondratyev85/raster_tracer#15]
To increase flexibility for users, it would be nice if smoothing of the lines could be optional.
A checkbox should be added to the GUI with the label "Line smoothing".

**Comment by mkondratyev85** [comment]
There was a bug in your implementation of smooth checkBox. Checking it had no effect on smooth option. 
Whether it was checked or not the tracing was without smoothing.

This commit fixed it: https://github.com/mkondratyev85/raster_tracer/commit/7830fdd793ed5ab29295566ff4ff83706029710a

**Comment by havatv** [comment]
> There was a bug in your implementation of smooth checkBox. Checking it had no effect on smooth option.
> Whether it was checked or not the tracing was without smoothing.
> 
> This commit fixed it: [7830fdd](https://github.com/mkondratyev85/raster_tracer/commit/7830fdd793ed5ab29295566ff4ff83706029710a)

I also noticed that.
The reason is that the state of the checkbox is not monitored, so you have to click on the plugin icon to get the right state.

![rastertracer_smooth](https://user-images.githubusercontent.com/1598812/92086550-9c51ba80-edca-11ea-8165-b2073fb65808.gif)

**Comment by havatv** [comment]
> There was a bug in your implementation of smooth checkBox. Checking it had no effect on smooth option.
> Whether it was checked or not the tracing was without smoothing.
> 
> This commit fixed it: [7830fdd](https://github.com/mkondratyev85/raster_tracer/commit/7830fdd793ed5ab29295566ff4ff83706029710a)

@mkondratyev85, I tested master in QGIS 3.14.1 after your commit. Everything worked as expected. Thanks!
