### ISSUE TITLE
Path not making a solid line, only red x's

### ISSUE THREAD

**Issue by posheadig** [mkondratyev85/raster_tracer#25]

**Comment by mkondratyev85** [comment]
This might be because your vector layer is beneath your raster layer and raster. If it's not the case please give more info

**Comment by posheadig** [comment]
Thanks for the response. I downloaded your latest zip and updated the qgis plugin for starters. 
Then I am uploading a geotiff file from https://ngmdb.usgs.gov/topoview/viewer/ into QGIS.
I then create new temporary scratch layer, with multilinestring/multicurve geometry type.
Set layer to trace as geotiff, make sure vector file is editable, follow pick color steps, but alas it does not create a solid line.

**Comment by mkondratyev85** [comment]
I reproduced this issue on my laptop. It looks like the problem is related to the projection. What I advice you is to reproject your desired map to WGS84 and load it in the project with WGS84 as main CS. At least it worked for me.

See https://github.com/mkondratyev85/raster_tracer/issues/12#issuecomment-633977240

**Comment by posheadig** [comment]
Ok I got it to work now. Yes the projection was the problem. Thank you for explaining.

**Comment by posheadig** [comment]
Hi again, I noticed that when I switched the CRS to WGS84, the projection no longer supported the correct coordinates... the raster tracer works but spits out a vector file with unusable coordinates. Any thoughts on this?

**Comment by posheadig** [comment]
Any possibility of adapting the code to work with NAD27?

**Comment by mkondratyev85** [comment]
Could you send me your project, including raster layer so I could figure it out on my laptop? mkondratyev85 at gmail.com
