### ISSUE TITLE
Doesn't work when CS of the map and the project doesn't match

### ISSUE THREAD

**Issue by mkondratyev85** [mkondratyev85/raster_tracer#26]
Something is wrong with the way raster-tracer finds indexes of the raster from coordinates of mouse.

See #25 and #12

**Comment by blacktesta** [comment]
Hi, Mikhail! Perhaps using .toLayerCoordinates instead of .toMapCoordinates should help

**Comment by mkondratyev85** [comment]
It looks like I found the problem. Maybe it is better to incorporate usage of  .toLayerCoordinates() in the future, but for now this fix should work.

Anyway, @blacktesta, thank you for inspiration.

**Comment by blacktesta** [comment]
@mkondratyev85, Great news! And thanks for the awesome plugin!
