### ISSUE TITLE
Plugin not working: AttributeError: 'PointTool' object has no attribute 'to_indexes

### ISSUE THREAD

**Issue by YinSun0** [mkondratyev85/raster_tracer#37]
I have been trying to use Raster Tracer to vectorize roads and rivers from raster images. I tried using as raster both my own raster images and also Open Street Maps QGIS tiles. None of works, giving the error:

> 2022-07-27T17:09:56     WARNING    Traceback (most recent call last):
>               File "/home/yinsun/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/raster_tracer/pointtool.py", line 492, in canvasReleaseEvent
>               self.state.click_lmb(mouseEvent, vlayer)
>               File "/home/yinsun/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/raster_tracer/pointtool_states.py", line 90, in click_lmb
>               if super().click_lmb(mouseEvent, vlayer) is False:
>               File "/home/yinsun/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/raster_tracer/pointtool_states.py", line 63, in click_lmb
>               if self.pointtool.to_indexes is None:
>              AttributeError: 'PointTool' object has no attribute 'to_indexes'

I am using the most recent QGIS, 3.26.1-Buenos Aires. And I have reinstalled Raster Tracer.

Any ideas?

**Comment by mkondratyev85** [comment]
First of all, it can only trace local raster files. So don't try to trace OpenStreetMaps. 

Second, check what color space your image has. For more detail see "What image can it trace" section in the README. Changes are, this will help.

It this isn't helping, check in in this issue and we'll figure out what's going on with your layer.

**Comment by YinSun0** [comment]
Quick questions:
- I am trying to trace raster layers of Open Street Map tiles, so it should work, shouldn'it?
- color space is correct
