### ISSUE TITLE
error  : The active layer must be a MultiLineString vector layer

### ISSUE THREAD

**Issue by jmjamison** [mkondratyev85/raster_tracer#38]
Apologies in advance - this is really a new user problem.  
QGIS version 3.22.14-Białowieża

The error:  : The active layer must be a MultiLineString vector layer.

I seem to not be able to create an appropriate vector layer.

**Comment by mkondratyev85** [comment]
Hi @jmjamison, thank you for using the plugin.

At the moment the plugin is only able to work with vector layers of MultiLineString. You can select the exact type of vector layer during the process of new layer creation. 

See:
https://docs.qgis.org/3.22/en/docs/user_manual/managing_data_source/create_layers.html#id17

**Comment by jmjamison** [comment]
The problem is really that I don't know how to correctly create the multilinestring layer.
