### ISSUE TITLE
Not working in 3.30?

### ISSUE THREAD

**Issue by 9ls1** [mkondratyev85/raster_tracer#39]
Thanks for this great plugin. I've used in with success in QGIS 3.28. In 3.30 I get an error message:
2023-03-10T12:25:55     WARNING    Traceback (most recent call last):
              File "C:\Users/abni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\raster_tracer\raster_tracer.py", line 246, in run
              self.tool_identify = PointTool(self.map_canvas, self.iface, self.turn_off_snap)
              File "C:\Users/abni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\raster_tracer\pointtool.py", line 131, in __init__
              self.rubber_band = QgsRubberBand(self.canvas(), False)
             TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool'

And the options are "grayed out" (e.g. not available to change trace color).

**Comment by mkondratyev85** [comment]
Hi @9ls1,

Thank you for using this plugin and for opening this issue. Sorry for the late response. The error indeed looks like they've changed something in the QgsRubberBand(). I would need to test this out myself. I will let you know when I find what's going on.

**Comment by mkondratyev85** [comment]
Hi @9ls1,

This issue is fixed in the newer version of the plugin.

**Comment by jo-chemla** [comment]
Thanks for the quick fix released on the [qgis plugin store](https://plugins.qgis.org/plugins/raster_tracer/)!
